### ISSUE TITLE
Nice use of wxPython! Can we adapt to OS dark mode?

### ISSUE THREAD

**Issue by m1ndy** [badabing2005/PixelFlasher#183] opened 2024-03-31 05:52 UTC
Nice use of wxPython! Can we adapt to OS dark mode?

MacOS, and Windows both support it at the platform level so all applications can just read that to switch themes. A perfunctory read of wxPython Forums seem to point that it is supported...

**Comment by badabing2005** [comment] 2024-03-31 15:24
Duplicate of #14

**Closed by badabing2005** 2024-03-31 15:24 UTC
