### ISSUE TITLE
Pixel 6a May Firmware failure patching magisk

### ISSUE THREAD

**Issue by coreycolman** [badabing2005/PixelFlasher#71] opened 2023-05-12 13:10 UTC
Hi, I've tried on current and previous version of PixelFlasher, hitting the same error when trying to patch the May Pixel 6a Factory Image file:

Extracting short SHA1 from magisk_patched_26100_40100d6b_7757d976.img ...
Traceback (most recent call last):
  File "Main.py", line 2067, in _on_patch_boot
  File "modules.py", line 1893, in patch_boot_img
  File "modules.py", line 1057, in extract_sha1
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 1: invalid start byte

I tried again with April Factory Image, patched fine on current PixelFlasher so this seems like an issue in the May Factory Image file from Google. Any ideas for a workaround?

**Comment by mike-s123** [comment] 2023-05-12 13:50
This is a duplicate of [issue #66](https://github.com/badabing2005/PixelFlasher/issues/66).

https://forum.xda-developers.com/t/pixelflasher-for-google-pixel-6a-support-thread.4482703/post-88489899

**Comment by coreycolman** [comment] 2023-05-12 15:48
> This is a duplicate of [issue #66](https://github.com/badabing2005/PixelFlasher/issues/66).
> 
> https://forum.xda-developers.com/t/pixelflasher-for-google-pixel-6a-support-thread.4482703/post-88489899

Yes it is. Thanks, I didn't click into that to before.

**Closed** 2023-05-12 15:50 UTC
