### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'unlocked'

### ISSUE THREAD

**Issue by V-Smeets** [badabing2005/PixelFlasher#156] opened 2024-02-08 18:25 UTC
Hello,

I have problems flashing my "panther" with PixelFlasher version 6.7.1.0. The PixelFlasher stops flahsing with the error message:
```
2024-02-08 19:00:13 Getting device: REDACTED state  ...
Rebooting device: REDACTED to bootloader ...
Fastboot waiting device: REDACTED for bootloader ...
device: REDACTED is now in bootloader mode.
Updating connected devices ...
Checking if the bootloader is unlocked ...

2024-02-08 19:00:23 ERROR: Encountered an error while flashing
Traceback (most recent call last):
  File "Main.py", line 3953, in _on_flash
  File "modules.py", line 3239, in flash_phone
AttributeError: 'NoneType' object has no attribute 'unlocked'
```

I have attached the support file. Check the last log file in it.
[support_2024-02-08_19-08-18.zip](https://github.com/badabing2005/PixelFlasher/files/14213234/support_2024-02-08_19-08-18.zip)

**Comment by badabing2005** [comment] 2024-02-08 18:57
Duplicate of: #153

**Closed by badabing2005** 2024-02-08 18:57 UTC
