### ISSUE TITLE
Freeze at "Fastboot Mode" step

### ISSUE THREAD

**Issue by PATAPOsha** [badabing2005/PixelFlasher#64] opened 2023-04-27 09:24 UTC
OS: macOS 12.4 (21F79) - MacbookPro M1 chip
PixelFlasher 4.8.2.0
Phone: Pixel 7 - panther-tq2a.230405.003.e1

I followed all steps from Usage (Basic Mode) guide
And got freeze on 10th step after phone rebooted into Fastboot Mode
![image](https://user-images.githubusercontent.com/14761219/234815995-9a211615-629d-46c3-8940-8670aa48eeec.png)

Phone is stuck in Fastboot Mode

In the Process Monitor I see that `fastboot` is using 100% CPU for about 30 mins already:
![image](https://user-images.githubusercontent.com/14761219/234819018-9c60ef07-101f-4ae3-aca3-e06b7daf750f.png)

Also, PixelFalsher does not respond:
![image](https://user-images.githubusercontent.com/14761219/234819206-89966b6c-bb3c-4a55-adfe-5b6294f3e13c.png)

I guess, this is an issue between emulation arm and x86 processes.
And I can continue root process manually, probably... But I'm not sure what exactly I need to do next

**Comment by PATAPOsha** [comment] 2023-04-27 10:18
I just pressed "Start" on the phone and it just booted. No root was applied.

**Comment by PATAPOsha** [comment] 2023-04-27 10:21
Tried same on my Windwos PC and got almost same result. Unless PixelFalsher dd not freeze, it just does not detect my Pixel.

Last logs from PixelFlasher:
```
"C:\Program Files\platform-tools\fastboot.exe" -s 28101FDH2004WC  flash radio radio-panther-g5300g-221229-230323-b-9800995.img
"C:\Program Files\platform-tools\fastboot.exe" -s 28101FDH2004WC reboot-bootloader  
ping -n 5 127.0.0.1 >nul
"C:\Program Files\platform-tools\fastboot.exe" -s 28101FDH2004WC  --skip-reboot update image-panther-tq2a.230405.003.e1.zip
echo rebooting to bootloader ...
"C:\Program Files\platform-tools\fastboot.exe" -s 28101FDH2004WC reboot bootloader
echo Sleeping 5-10 seconds ...
ping -n 5 127.0.0.1 >nul
ping -n 5 127.0.0.1 >nul
echo flashing pf_boot ...
"C:\Program Files\platform-tools\fastboot.exe" -s 28101FDH2004WC  flash init_boot pf_boot.img
echo rebooting to system ...
"C:\Program Files\platform-tools\fastboot.exe" -s 28101FDH2004WC reboot
___________________________________________________

2023-04-27 13:13:49 User Pressed Ok.

==============================================================================
 2023-04-27 13:13:49 PixelFlasher 4.8.2.0              Flashing Phone    
==============================================================================
Android Platform Tools Version: 33.0.3-8952118
Rebooting device 28101FDH2004WC to bootloader ...
Waiting 10 seconds ...
2023-04-27 13:14:06 No Device is selected!

2023-04-27 13:14:06 ERROR: Unable to detect the device.
Waiting 10 seconds ...
2023-04-27 13:14:16 No Device is selected!

2023-04-27 13:14:16 ERROR: Unable to detect the device.
```

The Phone is Fasboot Mode (same screenshot as in description of issue).

**Comment by PATAPOsha** [comment] 2023-04-27 10:52
Resolved `fastboot` detection issue installing latest drivers for Google USB Driver
https://developer.android.com/studio/run/win-usb

**Comment by PATAPOsha** [comment] 2023-04-27 10:57
However, there is still nor root in Magisk app...

PixelFlasher ended with logs:
```
...
extracting vendor_dlkm.img (41 MB) to disk... took 0.108s
archive does not contain 'vendor_dlkm.sig'
Resizing 'vendor_dlkm_b'                           OKAY [  0.007s]
Sending 'vendor_dlkm_b' (42032 KB)                 OKAY [  1.024s]
Writing 'vendor_dlkm_b'                            OKAY [  0.147s]
archive does not contain 'vendor_other.img'
Finished. Total time: 192.045s
rebooting to bootloader ...
Rebooting into bootloader                          OKAY [  0.001s]
Finished. Total time: 0.001s
Sleeping 5-10 seconds ...
flashing pf_boot ...
< waiting for 28101FDH2004WC >
Sending 'init_boot_b' (8192 KB)                    OKAY [  0.193s]
Writing 'init_boot_b'                              OKAY [  0.016s]
Finished. Total time: 0.212s
rebooting to system ...
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.000s
2023-04-27 13:46:56 Done!
Flashing elapsed time: 252 seconds
------------------------------------------------------------------------------
```

Full logs: https://pastebin.com/7emZ7nAZ

**Comment by badabing2005** [comment] 2023-04-27 14:59
For the MAC, I can't do anything, please see #51 #55 #56
For the windows, I don't see in the logs your provided, please provide support.zip from PizelFlasher, not only it gives me more details, it redacts sensitive information like name / device id ...

**Comment by PATAPOsha** [comment] 2023-04-27 19:20
@badabing2005  Here is support.zip
[support_2023-04-27_22-14-12.zip](https://github.com/badabing2005/PixelFlasher/files/11347201/support_2023-04-27_22-14-12.zip)

**Comment by badabing2005** [comment] 2023-04-27 21:45
How are you checking for root?
Is it because in PF you see that it's not rooted?
Have you checked [Basic usage](https://github.com/badabing2005/PixelFlasher#basic-mode) point 2?

Did you have a hidden Magisk at any point?

**Comment by PATAPOsha** [comment] 2023-04-28 06:31
> How are you checking for root?
I check it on the phone, in Magisk Manager app. There is "Installed: N/A; Zygisk: No; Ramdisk: Yes" in the Magisk section.
Also, after flashing - PixelFlasher identifies my phone with a ✗.
Also, after `adb shell` and `su` I get "Permission denied"

> Did you have a hidden Magisk at any point?
Yes, I had Magisk installed manually almost a year ago. It was hidden like a "Settings" app or smth. I had zygisk and "Magisk Hide" enabled. A couple of days ago, Android said that there is a new security update and updated with OTA.
After update, I restored original Magisk Manager app.
So I lost my root and found your project. I didn't want to flash it manually once again =)

**Comment by SyrmGIT** [comment] 2023-04-28 09:41
I'm having the same issue here, just completely frozen on "rebooting into fastboot".

I'm using the latest Google USB driver.

**Comment by badabing2005** [comment] 2023-04-28 15:23
> Yes, I had Magisk installed manually half a year ago. It was hidden like a "Settings" app or smth. I had zygisk and "Magisk Hide" enabled. A couple of days ago, Android said that there is a new security update and updated with OTA.
> After update, I restored original Magisk Manager app.
> So I lost my root and found your project. I didn't want to flash it manually once again =)

It sounds like you have two Magisk not playing nice with each other, this is a known issue.
Always unhide first before upgrading.

To resolve this follow these steps.
- See if you still have a settings App that is the old Magisk, if you do, uninstall and reboot
- If that solves the issue, your good, otherwise do the following
  - Install [TB Checker](https://play.google.com/store/apps/details?id=krypton.tbsafetychecker&hl=en_CA&gl=US) from play store, and run it, it should find the Magisk application and tell you the package name.
  - Uninstall the Magisk, it would probably first find your current version, it's ok to uninstall
  - After uninstall run TB checker again and see if it finds another Magisk, uninstall that too, and repeat until it does not find any Magisk
  - Install the current version of Magisk
  - reboot

**Comment by PATAPOsha** [comment] 2023-04-29 08:22
Uninstall Magisk app manually.
Then, uninstalled `xf.skb` - found by TB Checker - Xposed Check - Xposed Modules: Magisk Random Package Name: `xf.skb`
After that, it didn't find any Magisk before restart.
After restart, it found `com.topjohnwu.magisk` - uninstalled it and installed latest Magisk.
Root appeared after reboot!
Even all my Magisk modules are in place!
Thanks!

Should I close this issue? Since original issue is about Mac compatibility..

**Comment by badabing2005** [comment] 2023-04-29 12:33
Thanks for the update, happy it all worked.
Closing the issue.

**Closed by badabing2005** 2023-04-29 12:33 UTC
Labels: need more info

**Comment by vith** [comment] 2023-10-28 10:24
For anyone else who hits this issue, some more hints:

This happened to me on Windows 11 yesterday. The phone was not detected at all through USB during fastboot; nothing in device manager. I installed the Google USB driver which I confirmed was being used during ADB which was working. Still no fastboot devices.

I switched to a different machine with Ubuntu and it just worked.
