### ISSUE TITLE
Menu PixelFlasher > Quit PixelFlasher don't work as expected

### ISSUE THREAD

**Issue by knutlegrand** [badabing2005/PixelFlasher#187] opened 2024-04-05 10:37 UTC
When trying to quit PixelFlasher using the menu _PixelFlasher > Quit PixelFlasher_, a pop-up asking to save last husky OTA file is displayed instead of quitting the app.
The connected device is a Lynx (Pixel 7A) (information which would normally not be related  to quitting the app)
The two first lines of the menu _PixelFlasher_ refer to files related to Pixel 8 Pro. I don't know where it is coming from.

Here are 2 screenshots :

![Capture d’écran 2024-04-05 à 12 35 32](https://github.com/badabing2005/PixelFlasher/assets/120376273/49bb174b-b16e-4374-b8c7-d14f8fbc8707)

![Capture d’écran 2024-04-05 à 12 30 55](https://github.com/badabing2005/PixelFlasher/assets/120376273/4d805ca8-790e-4013-b337-9ab2afe8c7e3)

MacBook Pro (Retina, 13-inch, Early 2015)
MacOS 12.7.4 (Monterey)
PixelFlasher 6.9.0.2

**Comment by badabing2005** [comment] 2024-04-05 20:58
Give this one a try.
https://github.com/badabing2005/PixelFlasher/actions/runs/8575437421/artifacts/1389661729

**Comment by knutlegrand** [comment] 2024-04-06 09:22
Nothing has changed.
But (both versions) clicking on the red circle (upper left corner of the window) closes the app

**Comment by badabing2005** [comment] 2024-04-09 21:37
Fixed in v6.9.1.3

**Closed by badabing2005** 2024-04-09 21:37 UTC

**Comment by knutlegrand** [comment] 2024-04-10 11:01
Have installed v6.9.1.3. 

- The two first lines of the menu PixelFlasher still refer to files related to Pixel 8 Pro.
- _Menu "PixelFlasher > Quit PixelFlasher"_ still displays a pop-up asking to save last husky OTA file instead of quitting the app.
- _Menu "File > Quit"_ works

**Comment by roryokane** [comment] 2024-04-14 03:42
With PixelFlasher version 6.9.1.3, I see the exact same bugs as described in the first comment. That is:

- The app menu contains menu items about the Pixel 8 Pro. (I do not have that phone.)
- When I quit by clicking on the menu item, I am instead shown a prompt to download “husky-ota-uq1a.240205.004.a1-75ffdfec.zip”. After dismissing that prompt, the app does not quit.

OS: macOS Mojave 10.14.6
Hardware: MacBook Pro (15-inch, 2018)

## The release that introduced the bugs

I bisected [releases](https://github.com/badabing2005/PixelFlasher/releases) to see when the problem was introduced.

The app menu is buggy in these releases:

- [v6.9.1.3](https://github.com/badabing2005/PixelFlasher/releases/tag/v6.9.1.3)
- [v6.8.4.0](https://github.com/badabing2005/PixelFlasher/releases/tag/v6.8.4.0)
- [v6.7.1.0](https://github.com/badabing2005/PixelFlasher/releases/tag/v6.7.1.0)
- [v6.7.0.0](https://github.com/badabing2005/PixelFlasher/releases/tag/v6.7.0.0)

<img width="547" alt="PixelFlasher v6.7.1.0 – buggy app menu" src="https://github.com/badabing2005/PixelFlasher/assets/79168/c5feb174-1b5e-43b5-a8b5-992826cf88fd">

The app menu works as it should in this release:

- [v6.6.1.0](https://github.com/badabing2005/PixelFlasher/releases/tag/v6.6.1.0)

<img width="549" alt="PixelFlasher v6.6.1.0 – working app menu" src="https://github.com/badabing2005/PixelFlasher/assets/79168/6787b1d8-3850-4b9c-9141-bd0c45feff7f">

##  The code change that introduced the bugs

The [diff](https://github.com/badabing2005/PixelFlasher/compare/v6.6.1.0...v6.7.0.0) between those tags shows only one commit. The changes in this commit must have caused the bug: [`4f6ef29` “- Added history to device image selection (Max 16)”](https://github.com/badabing2005/PixelFlasher/commit/4f6ef29415dca172620d42156688fe1c9cf3a417)

**Comment by badabing2005** [comment] 2024-04-14 11:25
Thanks for the investigation, but I'm not reverting anything.
There are a lot more menu items now than there was in 6.6.1.0, I'm not removing any features just to cator to MacOS esotheric intricacies.
I added the `Exit` menu under File menu, just like it is on all other platforms, do not use App menu that MacOS adds, registering the correct menu ID doesn't seem to be working.
I even commented out the registring of the menuid, but someone the OS is still picking it up.
Could be a bug in OS (you're probably using newer OS) or WxPython handling of it.

In any case if this is bothering you, it's open source, feel free to make a PR that properly fixes this without removing any functionality.

**Comment by roryokane** [comment] 2024-04-15 02:42
I guess I didn’t mention that the bug I cared about most was that the “About PixelFlasher” menu item was missing. In macOS apps that menu item is always at the top of the application menu, as it was in [v6.6.1.0](https://github.com/badabing2005/PixelFlasher/releases/tag/v6.6.1.0). That was visible in the screenshots, but I didn’t point it out before.

However, I found a workaround for this, too. The About PixelFlasher dialog can be opened from Help > About PixelFlasher:

<img width="358" alt="Help > About PixelFlasher" src="https://github.com/badabing2005/PixelFlasher/assets/79168/92534ca4-111c-44d6-ae3a-571fa684b8d2">

Now that I know I can get all the same functionality that is normally in the application menu, just in harder-to-remember places, I am less concerned about the application menu containing buggy items.

It would be less confusing for users if the app followed the conventions of each platform it runs on, or if non-supported menus were empty rather than containing buggy menu items. However, I understand that you have limited time to work on PixelFlasher. I hope that at some point, I or another user have time to build the app on macOS and figure out whether a targeted reversion of some of the changes in https://github.com/badabing2005/PixelFlasher/commit/4f6ef29415dca172620d42156688fe1c9cf3a417 can fix the macOS application menu without breaking any existing functionality.

**Comment by badabing2005** [comment] 2024-04-15 13:52
> It would be less confusing for users if the app followed the conventions of each platform it runs on, or if non-supported menus were empty rather than containing buggy menu items.

I tried, but if the platform of choice doesn't want to cooperate and insert buggy menu items, what do you do?

Without getting too technical, the way this works in WxPython and MacOS is you create an Exit menu item as `wx.ID_EXIT` and About menu item as `wx.ID_ABOUT`
Each of these has unique id, which is different on each platform.
WxPython takes care of registering this ID as Exit or About on MacOS so that they show up under application menu.
The problem lies in the way the id value is translated / handled by the OS or WxPython (totally out of my control), which ends up conflicting with one of the other menu ids.
In this case it happened to conflict with husky download link as stated in this ticket.

I had tried a workaround instead of creating `wx.ID_EXIT` by creating a unique id using `wx.ID_ANY`
And then registering this to be an exit menu. `wx.App.SetMacExitMenuItemId(exit_item.GetId())`
And even though wx.ID_ANY had created absolutely unique ID that did not conflict with any ID, in the translation (wxPython) or the interpretation (MacOS) that ID was translated to match Husky download ID.

I have yet made another workaround, but this will be my last attempt, as I have spent way more time on this than it warrants, people can get used to finding the menu items under File or Help

Please try this build and report back.
https://github.com/badabing2005/PixelFlasher/actions/runs/8690096474

**Comment by roryokane** [comment] 2024-04-15 18:20
# The About and Quit menu items

The About and Quit menu items in that build work! Thank you.

<img width="596" alt="application menu with PixelFlasher Build for MacOS 11 #38" src="https://github.com/badabing2005/PixelFlasher/assets/79168/b28d80cc-6752-4736-a50d-0e8ec636b0b5">

“About PixelFlasher” successfully opens the dialog, and “Quit PixelFlasher” successfully quits. The keyboard shortcut <kbd>⌘Q</kbd> also still successfully quits.

With this change, “About PixelFlasher” is no longer in the Help menu and “Quit PixelFlasher” is no longer in the File menu:

<img width="72" alt="File menu with PixelFlasher Build for MacOS 11 #38" src="https://github.com/badabing2005/PixelFlasher/assets/79168/440595e8-361d-4ce4-9d61-9294780e270e"> <img width="178" alt="Help menu with PixelFlasher Build for MacOS 11 #38" src="https://github.com/badabing2005/PixelFlasher/assets/79168/9622f348-af53-421e-9289-4c409db12379">

This makes sense to me: each menu item is only found in one place.

# The remaining erroneous menu item

In the application menu, there is still a single erroneous menu item “14.0.0 (UD1A.230803.041, Oct 2023) (Pixel 8 Pro)” that, when clicked, asks where to save “husky-ota-ud1a.230803.041-cca7e111.zip”. (I mention the full name for the aid of future searchers.)

<img width="385" alt="“14.0.0 (UD1A.230803.041, Oct 2023) (Pixel 8 Pro)” highlighted in application menu with PixelFlasher Build for MacOS 11 #38" src="https://github.com/badabing2005/PixelFlasher/assets/79168/5d7ca7a3-b758-4942-a9c0-d16449466881"> <img width="353" alt="file save dialog for “husky-ota-ud1a.230803.041-cca7e111.zip”" src="https://github.com/badabing2005/PixelFlasher/assets/79168/c79a4623-7e4b-4fcb-bf8e-2e0113cfcd06">

As I think you already knew but I only just understood, this menu item should instead be in the Google Images > Phones > husky (Pixel 8 Pro) > Ota menu, where it is not present. [Google’s list of OTA images for husky](https://developers.google.com/android/ota#husky) includes the Oct 2023 one.

<img width="556" alt="Google Images > Phones > husky (Pixel 8 Pro) > Ota menu in PixelFlasher Build for MacOS 11 #38" src="https://github.com/badabing2005/PixelFlasher/assets/79168/f45cd537-56fe-42d4-8d36-c01e110fb600">

At least this is a much less confusing situation than before. Because the application menu has a working “About PixelFlasher” menu item, users will not be trying to open the About PixelFlasher dialog by clicking on random menu items. Some users may may worry that the menu item describes what software will be installed on their phone, or may experimentally click on that menu item and be confused by the download. But if they use the rest of the app and see that it installs the correct software, or if they search for the name of the menu item and find this issue, they should gain confidence that the menu item is harmless.

## My understanding of the cause of this bug

Thanks to your explanation of wxPython and IDs, I understand now that the numeric ID generated for this menu item by this line of `GoogleImagesMenu.__init__`:

https://github.com/badabing2005/PixelFlasher/blob/c63f178b6e085b8236a024901a88064c9998c89c/Main.py#L366

is coinciding with the unique ID of some menu item that belongs in the application menu on macOS according to wxPython.

I also understand that when you previously tried creating a menu item using `wx.ID_ANY`, which the wxPython documentation said will always be unique, the menu item somehow still ended up being recognized as a special ID whose menu item belongs in the application menu. So I won’t suggest any solutions using `wx.ID_ANY`.

## Possible fixes

Since this menu item is being placed under the first divider of the application menu, I suspect that its ID is conflicting with “Preferences…”, a menu item that is generally in that location in macOS apps:

<img width="204" alt="“Preferences…” menu item in Terminal application menu" src="https://github.com/badabing2005/PixelFlasher/assets/79168/f10fba91-e9bf-4ec8-a340-20238ae25fca">

In [wxPython’s list of stock items][wxPython stock items docs], `wx.ID_PREFERENCES` looks like the ID for this.

I see two possible ways to prevent this OTA download menu item from being assigned this ID. The fix might only work if both changes are made.

#### 1. Ensure `generate_unique_id()` cannot return `wx.ID_PREFERENCES`

Add `wx.ID_PREFERENCES` to the list of exceptions you added in this commit’s workaround within `generate_unique_id()`:

https://github.com/badabing2005/PixelFlasher/blob/c63f178b6e085b8236a024901a88064c9998c89c/Main.py#L262

By replacing that line with code like this:

```python
# Workaround for https://github.com/badabing2005/PixelFlasher/issues/187
# This is a subset of https://docs.wxpython.org/stock_items.html#stock-items
wx_python_stock_ids = [wx.ID_EXIT, wx.ID_ABOUT, wx.ID_PREFERENCES]
while unique_id in wx_python_stock_ids:
```

Optional: If we wanted to pre-emptively avoid any other menu item ID collision bugs, we could even add all 72 stock IDs listed in [wxPython’s stock items page][wxPython stock items docs] to `wx_python_stock_ids`. The downsides would be that the  the list in the code might get out of date as wxPython is updated, so we could not rely on such a fix prevent _all_ such problems in the future, and that we would see irrelevant build errors if wxPython ever removes one of those IDs.

#### 2. Use `wx.ID_PREFERENCES` for another menu item

When creating PixelFlasher’s “Settings” menu item (the equivalent of “Preferences…”) here:

https://github.com/badabing2005/PixelFlasher/blob/c63f178b6e085b8236a024901a88064c9998c89c/Main.py#L1229

Give it `wx.ID_PREFERENCES` instead of `wx.ID_ANY`. This will hopefully place this menu item in the application menu on macOS in place of “14.0.0 (UD1A.230803.041, Oct 2023) (Pixel 8 Pro)”.



I don’t have a Python environment set up to test these two possible changes, but let me know if you’d like them in the form of a PR rather than the written description above.

[wxPython stock items docs]: https://docs.wxpython.org/stock_items.html#stock-items

**Comment by roryokane** [comment] 2024-04-15 22:08
Yep, that seems to have fixed it. Thanks again.

<img width="206" alt="PixelFlasher application menu with Settings menu item in place of the erroneous OTA download menu item" src="https://github.com/badabing2005/PixelFlasher/assets/79168/c250b80b-1009-4edc-824e-dec70943624d">

This moved “Settings” menu item still opens the Advanced Configuration Settings dialog, as expected. And “14.0.0 (UD1A.230803.041, Oct 2023) (Pixel 8 Pro)” is back where it belongs within the Google Images menu:

<img width="834" alt="“14.0.0 (UD1A.230803.041, Oct 2023) (Pixel 8 Pro)” is back in the husky Ota menu" src="https://github.com/badabing2005/PixelFlasher/assets/79168/25ebe9aa-23f7-49bf-b708-a4719540d1d5">

## Empty File menu

By the way, this fix has the side effect that there is an empty File menu on macOS:

<img width="229" alt="File menu is empty" src="https://github.com/badabing2005/PixelFlasher/assets/79168/89b880e2-0d74-4e70-bdd2-78fa7066996e">

But I think this situation – a well-organized application menu plus an empty File menu – is better than keeping Settings in the File menu on macOS.

To hide the File menu when it’s not used, it might work to make the [`self.menuBar.Append(file_menu, "&File")` call](https://github.com/badabing2005/PixelFlasher/blob/014cc81592b49f53c6316b2b0e507c3d0e05cfb5/Main.py#L1571) conditional on [`file_menu.GetMenuItemCount()`](https://docs.wxpython.org/wx.Menu.html#wx.Menu.GetMenuItemCount) or something. But that feels like a hacky workaround. wxPython probably has a simpler way they expect users to add menus that should exist only on certain platforms. I’m not too fussed about the empty menu, so I’m happy to leave exploring those solutions for another time.

**Comment by roryokane** [comment] 2024-04-16 00:17
I looked for existing solutions to the wxPython empty File menu problem. I didn’t find any, but I did find a _lack_ of a known solution on the [wxPython wiki page “Optimizing for Mac OS X”](https://wiki.wxpython.org/Optimizing%20for%20Mac%20OS%20X):

> That results in […] an "About MyApp" menu item in the Application menu on MacOS. (Note that **it also creates an empty "Help" menu, but presumably you can fill that up with, well, Help.** :) --MarcHedlund) There are similar tricks for Preferences and Quit menus, which are moved to the "Application" menu.

In this case, we have no other menu items that belong in the File menu to “fill [it] up” with, so that page’s advice doesn’t help. The lack of an answer there suggests that a conditional like the one in your last comment would, sadly, be necessary to hide the empty menu.

**Comment by badabing2005** [comment] 2024-04-16 02:09
See if this works.
https://github.com/badabing2005/PixelFlasher/actions/runs/8698861464

**Comment by roryokane** [comment] 2024-04-16 02:23
Sadly, it does not. That build successfully hides the File menu on macOS:

<img width="609" alt="full menu bar of PixelFlasher build from action 8698861464 – it does not include File menu" src="https://github.com/badabing2005/PixelFlasher/assets/79168/50c5ba33-9b99-4d43-85e1-8cf01c1fd651">

But it also hides the Settings menu item from the application menu:

<img width="196" alt="PixelFlasher application menu without Settings menu item" src="https://github.com/badabing2005/PixelFlasher/assets/79168/22f0b5f5-3eaa-4cb0-aa1f-14ea85e22627">

**Comment by badabing2005** [comment] 2024-04-16 03:36
Interesting, and not making sense.
I was afraid that something like this might happen, but I would have expected all menus from File to disappear.
Seeing that the exit one is still showing up but not the settings, totally does not make sense.
But I expect that from Apple ;)

**Comment by roryokane** [comment] 2024-04-17 16:12
> … I would have expected all menus from File to disappear.
> Seeing that the exit one is still showing up but not the settings, totally does not make sense.

I don’t know whether it’s macOS or wxPython that ensured the “Quit PixelFlasher” menu item was present, but I can guess why either software would do this. I hope my explanation will reduce your confusion.

If a focusable app did not have a “Quit \<app\>” menu item, the user could only close the app [using the Dock](https://github.com/badabing2005/PixelFlasher/assets/79168/398eabac-d36e-49ec-871b-9fbdbcd1eb9f) or [Activity Monitor](https://github.com/badabing2005/PixelFlasher/assets/79168/1ad3249e-e153-478e-9524-e70ed7176eff). This would be analagous to a program on Windows without ![a window’s red X close button](https://github.com/badabing2005/PixelFlasher/assets/79168/097b0bba-3fa6-48c4-94af-7a4b03788b16) in the top right – the user would be forced to close the program using the Taskbar context menu or Task Manager. It makes sense to prevent this by forcing a Quit menu item to appear.

But why does macOS need a dedicated menu item to quit when windows on macOS have a <img width="28" alt="macOS red window close button" src="https://github.com/badabing2005/PixelFlasher/assets/79168/90eacf7c-5087-4340-9bfb-30d45dba9911"> button at their top left corner? It’s because macOS separates the concepts of open windows and open apps. Clicking the red button closes the window but not necessarily the app. For example, Google Chrome can be open without any tabs, and Microsoft Word can be open without any documents. When an app is open with no windows, its menu is still visible at the top of the screen, and apps only enable menu items that don’t require an open document, such as “File” > “Open…”.

Why support this complicated concept of apps with no open windows? One benefit is that when a user keeps such an app open, when they later want to open a document in that app, they can avoid having to wait for the app itself to load. (This was a bigger deal when Mac OS was first designed and computers were slower.) Keeping a windowless app open also keeps the app in the Dock as a drag-and-drop target.

Though all apps are quittable, not all apps have preferences (settings). That must be why PixelFlasher’s “Settings” menu item was not forced to appear when it was not registered.
