### ISSUE TITLE
PixelFlasher crashes on selecting Phone image

### ISSUE THREAD

**Issue by brnl** [badabing2005/PixelFlasher#88] opened 2023-07-16 02:29 UTC
I have an issue running PixelFlasher_Ubuntu_22_04 (v5.5.1.0) on Manjaro (Arch). I hope you can support me without yelling to me to install Ubuntu, but if that's the case, I'm sincerely sorry for wasting your time! 🙂
```sh
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	23.0.0
Codename:	UltimaThule
```

## Application crashes
I have several application crashes, the main one after selecting the Phone Image zip file. It freezes for a second and then just disappears. When running from a terminal I just get `Gdk-Message: 04:15:57.355: Error flushing display: Broken pipe`.
**Note:** Sometimes it doesn't crash after selecting the image, then it crashes consistently when pressing "Process".

I tried two different adb versions:
```
$ adb version
Android Debug Bridge version 1.0.41
Version 34.0.1-android-tools
Installed as /usr/bin/adb

$ ~/Downloads/platform-tools/adb version
Android Debug Bridge version 1.0.41
Version 34.0.4-10411341
Installed as /home/<redacted>/Downloads/platform-tools/adb
Running on Linux 6.4.2-3-MANJARO (x86_64)
```

The image I was trying to open was `13.0.0 (TQ3A.230705.001, Jul 2023)` ([oriole-tq3a.230705.001-factory-efff090e.zip](https://dl.google.com/dl/android/aosp/oriole-tq3a.230705.001-factory-efff090e.zip)).

The app isn't very verbose with logging or console messages, I think. What else can I provide you to help me debug or even resolve this issue?

**Comment by badabing2005** [comment] 2023-07-16 14:29
Why would I yell at you? have you seen me yell at others?
Issues are for reporting issues, and that is exactly what you have done, if they are none-issue, they get marked as such and closed.

Speaking of the issue you are experiencing, I would like to get a support file.
Just launch PixelFlasher, and hit that big support button or generate one from the help menu and submit that please.

Have you tried this?
https://aur.archlinux.org/packages/pixelflasher-bin
Although I don't expect it to be different as it is based of Ubuntu_22.0.4 build, but it doesn't hurt to try.

**Comment by brnl** [comment] 2023-07-16 15:46
I would be yelling at me, haha! Thanks for your reply.

The [pixelflasher-bin](https://aur.archlinux.org/packages/pixelflasher-bin) came much further but still crashed. I have exported the support file here: [support_2023-07-16_17-22-32.zip](https://github.com/badabing2005/PixelFlasher/files/12064452/support_2023-07-16_17-22-32.zip)

I see the old logs are there also, so maybe it helps. Please let me know what else I could test!

Thanks again!

**Comment by brnl** [comment] 2023-07-16 15:53
That's weird, I have tried another time and now it succeeded in the AUR version. Here's the updated support file: 
[support_2023-07-16_17-52-45.zip](https://github.com/badabing2005/PixelFlasher/files/12064478/support_2023-07-16_17-52-45.zip)

**Comment by brnl** [comment] 2023-07-16 15:58
Yeah, bummer, that crashed again: 
[support_2023-07-16_17-57-56.zip](https://github.com/badabing2005/PixelFlasher/files/12064488/support_2023-07-16_17-57-56.zip)

**Comment by brnl** [comment] 2023-07-16 16:17
One brainfart, since the closing error on the console is `Gdk-Message: 17:57:36.543: Lost connection to Wayland compositor.`, could it maybe be that Wayland is not happy to wait for the 'sleep' in the script?

And, totally off-topic, why is there an `echo` in front of the  `fastboot [...] flash boot pf_boot.img` line? That is, actually, where it crashed the last time, now I looked further in it.

```sh
#!/bin/sh
# This is a generated file by PixelFlasher v5.5.1.0
# cd /home/REDACTED/.local/share/PixelFlasher/factory_images/oriole-tq3a.230705.001
# pf_boot.img: /home/REDACTED/.local/share/PixelFlasher/boot_images4/dc72b385d37b4f7cb2b0039438f906b223acb9cd/magisk_patched_26100_dc72b385_5edfa594.img
# Android Platform Tools Version: 34.0.4-10411341

echo "/home/REDACTED/Downloads/platform-tools/fastboot" -s REDACTED  flash bootloader bootloader-oriole-slider-1.2-9883526.img
"/home/REDACTED/Downloads/platform-tools/fastboot" -s REDACTED reboot-bootloader  
sleep 5
echo "/home/REDACTED/Downloads/platform-tools/fastboot" -s REDACTED  flash radio radio-oriole-g5123b-116954-230511-b-10112789.img
"/home/REDACTED/Downloads/platform-tools/fastboot" -s REDACTED reboot-bootloader  
sleep 5
echo "/home/REDACTED/Downloads/platform-tools/fastboot" -s REDACTED  --skip-reboot update image-oriole-tq3a.230705.001.zip

echo rebooting to bootloader ...
"/home/REDACTED/Downloads/platform-tools/fastboot" -s REDACTED reboot bootloader

echo Sleeping 5-10 seconds ...
sleep 5
sleep 5

echo flashing pf_boot ...
echo "/home/REDACTED/Downloads/platform-tools/fastboot" -s REDACTED  flash boot pf_boot.img
^^^^--- > THIS ONE

echo rebooting to system ...
"/home/REDACTED/Downloads/platform-tools/fastboot" -s REDACTED reboot
```

**Comment by badabing2005** [comment] 2023-07-16 20:36
The echo is because you chose `Dry Run` which echoes the commands that it would run without actually running them, other than getting into fastboot / fatsbootd mode.

**Comment by brnl** [comment] 2023-07-16 20:44
You are right! So then it's yet unclear why it crashed for me. I manually ran the last two steps (flash boot pf_boot.img and reboot) and that finished it successfully for me.

**Comment by badabing2005** [comment] 2023-07-16 20:47
I don't see a crash in the logs.
Is it still happening?

**Comment by brnl** [comment] 2023-07-16 20:54
I think the crash happened here: support_2023-07-16_17-57-56.zip/logs/PixelFlasher_2023-07-16_17h47m32s.log

That file ends with the line `Sleeping 5-10 seconds ...`
After that it should have flashed `pf_boot.img` at that point the app just disappeared. That's why I correlate the console error 'Gdk-Message: 17:57:36.543: Lost connection to Wayland compositor.' to the 10 seconds sleep. But I have no idea.

I have flashed my phone now so it's harder to test but if you need to try something, I think I can re-flash it, right?

**Comment by badabing2005** [comment] 2023-07-17 13:30
I can't see how on the sleep command the program would crash
Here's the complete script that it ran

```
#!/bin/sh
# This is a generated file by PixelFlasher v5.5.1.0
# cd /home/boss/.local/share/PixelFlasher/factory_images/oriole-tq3a.230705.001
# pf_boot.img: /home/boss/.local/share/PixelFlasher/boot_images4/dc72b385d37b4f7cb2b0039438f906b223acb9cd/magisk_patched_26100_dc72b385_5edfa594.img
# Android Platform Tools Version: 34.0.4-10411341

"/home/boss/Downloads/platform-tools/fastboot" -s REDACTED  flash bootloader bootloader-oriole-slider-1.2-9883526.img
"/home/boss/Downloads/platform-tools/fastboot" -s REDACTED reboot-bootloader  
sleep 5
"/home/boss/Downloads/platform-tools/fastboot" -s REDACTED  flash radio radio-oriole-g5123b-116954-230511-b-10112789.img
"/home/boss/Downloads/platform-tools/fastboot" -s REDACTED reboot-bootloader  
sleep 5
"/home/boss/Downloads/platform-tools/fastboot" -s REDACTED  --skip-reboot update image-oriole-tq3a.230705.001.zip

echo rebooting to bootloader ...
"/home/boss/Downloads/platform-tools/fastboot" -s REDACTED reboot bootloader

echo Sleeping 5-10 seconds ...
sleep 5
sleep 5

echo flashing pf_boot ...
"/home/boss/Downloads/platform-tools/fastboot" -s REDACTED  flash boot pf_boot.img

echo rebooting to system ...
"/home/boss/Downloads/platform-tools/fastboot" -s REDACTED reboot
```

as you can see there are previous sleep commands that did not cause a crash, and there are also previous fastboot commands that did not cause a crash.
Perhaps it is system issue .
Does this happen every time?

**Comment by badabing2005** [comment] 2023-07-28 01:44
Is this consistently reproducible? or it was a one time thing?
I'm not going to rule out a potential issue, but I don't have a way to reproduce this or have enough data to troubleshoot.

If you can reproduce this, we could try to narrow it down with your help.

**Comment by brnl** [comment] 2023-07-28 08:14
I'm sorry to leave you hanging. I'll try to reproduce this asap. I'm currently using my phone so it's scary to mess with it.

**Comment by badabing2005** [comment] 2023-08-18 18:45
I'm closing this issue, if you can reproduce or have more data, please post and I'll reopen it.

**Closed by badabing2005** 2023-08-18 18:45 UTC
